export const languages = [
  { code: "en", label: "English", subLabel: "" },
  { code: "vi", label: "Tiếng Việt", subLabel: "Vietnamese" },
  { code: "zh", label: "简体中文", subLabel: "Chinese" },
  { code: "hi", label: "हिन्दी", subLabel: "Hindi" },
  { code: "es", label: "Español", subLabel: "Spanish" },
  { code: "ar", label: "العربية", subLabel: "Arabic" },
  { code: "fr", label: "Français", subLabel: "French" },
  { code: "pt", label: "Português", subLabel: "Portuguese" },
  { code: "ru", label: "Русский", subLabel: "Russian" },
  { code: "bn", label: "বাংলা", subLabel: "Bengali" },
  { code: "id", label: "Bahasa", subLabel: "Indonesia" },
  { code: "ja", label: "日本語", subLabel: "Japanese" },
  { code: "th", label: "ไทย", subLabel: "Thai" },
  { code: "ko", label: "한국어", subLabel: "Korean" },
  { code: "tr", label: "Türkçe", subLabel: "Turkish" },
  { code: "fil", label: "Filipino", subLabel: "Filipino" },
  {
    code: "pt-br",
    label: "Português",
    subLabel: "Brazil",
  },
  { code: "fa", label: "فارسی", subLabel: "Persian" },
];
